### ISSUE TITLE
Remove "Done"

### ISSUE THREAD

**Issue by danrabbit** [mank319/Go-For-It#10]
I'm not sure what the purpose of the "Done" button is. It doesn't seem to do anything different from what "Pause" does. It also seems to do nothing if the timer is not active. If the button does nothing in a certain case, it should be insensitive. But if it doesn't do anything unique, I think it's probably better not to have it.

**Comment by mank319** [comment]
Update: I guess the aforementioned problem is related to `win.show_all ()` making all children of the main window visible recursively. Thus it does not matter if I set it to invisible before.

**Comment by fredmwangi** [comment]
@danrabbit 
![empty](https://cloud.githubusercontent.com/assets/10415947/5736838/9101e1d4-9ba8-11e4-89f5-81bba48d0ca8.gif)
![complete_notdonenext2](https://cloud.githubusercontent.com/assets/10415947/5738112/6d6bff1c-9bb6-11e4-851f-d3521e99d1c2.gif)

**Comment by mank319** [comment]
We finally fixed the Done button behaviour! 
Thanks @fredmwangi for your contributions!
