### ISSUE TITLE
Sound notifications

### ISSUE THREAD

**Issue by PerigGouanvic** [mank319/Go-For-It#102]
Yeah, like others on this page http://manuel-kehl.de/projects/go-for-it/, I'd love to have notification sounds.

How many times I was so absorbed by my work that I did not notice my time was up!

**Comment by JMoerman** [comment]
If you're not using Windows, libnotify is used for notifications. The desktop environment that I'm using does produce sounds on notifications, you may want to check if you can configure something similar for your setup. I do not currently have the time to implement this.

**Comment by wi24rd** [comment]
Hi, I'm using xfce in Ubuntu 19.10, which doesn't have sound default when notification comes. Maybe it can be done by some customization.
But it would better if I can choose a audio file such like "/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga" to play when the "reminder before task ends" time comes.

**Comment by wi24rd** [comment]
xfce4-notifyd doesn't support sound, sadly. 
https://docs.xfce.org/apps/notifyd/spec

**Comment by JMoerman** [comment]
Implemented in e1adf25cd53de91de5aab04c57932e0b0572e97b (libcanberra)
