### ISSUE TITLE
Timer works like a pomodoro

### ISSUE THREAD

**Issue by sic-f** [mank319/Go-For-It#105]
Hi, great app you have.

Would be great also if the timer can be configured like a pomodoro.

There would be a longer break setting after x times of short breaks.

And the timer should automatically start after breaks.

Thanks!

**Comment by JMoerman** [comment]
Sounds good.

Unfortunately I do not have much time available at the moment. So it could take a long time before I get around to doing something like this.

**Comment by sic-f** [comment]
It's alright. Goodluck!

**Comment by baimafeima** [comment]
I second this. Would be great to have it with pomodoro capabilties.

**Comment by JMoerman** [comment]
This functionality is now present in master.
