### ISSUE TITLE
Go For It - AppImage

### ISSUE THREAD

**Issue by MichaelTunnell** [mank319/Go-For-It#109]
I just found out that the AppImage developer, @probono, made an AppImage for Go For It.

https://bintray.com/probono/AppImages/Go_For_It#files

**Comment by iamonkara** [comment]
Can someone please create the latest  AppImage release for GoForit ?

**Comment by MichaelTunnell** [comment]
it is unlikely since they use Flatpaks now so just use that version instead

**Comment by iamonkara** [comment]
and where are the latest version of GoForit available in flatpaks ?

**Comment by MichaelTunnell** [comment]
https://flathub.org/apps/details/de.manuel_kehl.go-for-it
