### ISSUE TITLE
optionally support creation & completion dates

### ISSUE THREAD

**Issue by jpouellet** [mank319/Go-For-It#113]
These are both parts of the Todo.txt format and documented here:
- [creation dates](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#rule-2-a-tasks-creation-date-may-optionally-appear-directly-after-priority-and-a-space)
- [completion dates](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space)

It would be nice to have an option to set these automatically (and perhaps another option to not display them)

I feel this is not really feature creep, since they are explicitly already part of the very minimal standard format and supported & used by other tools & people.

**Comment by jpouellet** [comment]
If I still use your app in a few weeks I'll probably implement this myself.

**Comment by JMoerman** [comment]
This has already been requested here: https://github.com/mank319/Go-For-It/issues/55
Other than that I agree that it would indeed be nice to have that option.

**Comment by jpouellet** [comment]
Noted. Closing as duplicate.
