### ISSUE TITLE
Place tabs in same place as menu button

### ISSUE THREAD

**Issue by nick87720z** [mank319/Go-For-It#118]
For now tabs always have own bar.
I'm not sure, is it required by [Elementary HIG](https://elementary.io/docs/human-interface-guidelines#notebooks), at least i could not find any headerbar mention, appart not about search/find difference.

This , of course, may need to make tabs itself as compact as possible, while not breaking HIG...
I guess, horizontal label spacing could be at least same as vertical (of course, if it is set in program.... might be in theme too:) ).

Yet, in this case there could be icons instead of text.
Images for "timer" and "done" are enough obvious, though what to assign for tasks button, to keep it simple...

**Comment by JMoerman** [comment]
One thing you should know is that I'm planning to add one extra element to the headerbar: a button to switch to a selection screen for lists. (As I'm planning to add the option to have more than one list, eventually also multiple back ends.)

If the StackSwitcher would be moved to the headerbar with the text replaced with icons or if it would replaced with 3 icon buttons the headerbar would get a bit crowded. Perhaps the extra vertical space can justify this, though.
It may be worth experimenting with this.

First I want to merge https://github.com/mank319/Go-For-It/tree/listbox-dnd, but I want to be reasonably certain that it doesn't introduce any bugs.

**Comment by JMoerman** [comment]
This issue was moved to JMoerman/Go-For-It#5
