### ISSUE TITLE
Ubuntu 17

### ISSUE THREAD

**Issue by paveltaran** [mank319/Go-For-It#119]
Not install on ubuntu 17 :(

**Comment by JMoerman** [comment]
Should be fixed in the listbox-dnd branch.
I need to do some tests on a few more platforms, merge that branch and update the packaging information and launchpad recipe.
If all goes well https://launchpad.net/~go-for-it-team/+archive/ubuntu/go-for-it-daily should have new packages later this day.

**Comment by JMoerman** [comment]
New packages for Ubuntu 17.04 and 17.10 are now available on https://launchpad.net/~go-for-it-team/+archive/ubuntu/go-for-it-daily
