### ISSUE TITLE
Add an appdata file

### ISSUE THREAD

**Issue by baimafeima** [mank319/Go-For-It#121]
For reference: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

**Comment by AsavarTzeth** [comment]
Actually I have made [one already](https://github.com/flathub/de.manuel_kehl.go-for-it/blob/master/de.manuel_kehl.go-for-it.appdata.xml), I just did not have time to make a pull request.

Part of the reason why I got delayed was that I tried to make some screenshots that followed the specification recommendations. That is quite difficult with an application that does not look great at window sizes that have an aspect ratio of 16:9.

**Comment by JMoerman** [comment]
Thanks to @AsavarTzeth an appdata file is now included. I will update it at a later time. (Include a screenshot/screenshots, adapt the description a bit (reference to "_my Todo.txt Kupfer Plugin_" isn't clear and should probably be removed.))
