### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by baimafeima** [mank319/Go-For-It#122]
Could you make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by JMoerman** [comment]
I've added release information to the releases since 1.4.7 and will make sure it is included with next releases: https://github.com/mank319/Go-For-It/releases
Was this what you had in mind?

**Comment by baimafeima** [comment]
@JMoerman Awesome, thanks!

**Comment by JMoerman** [comment]
https://github.com/mank319/Go-For-It/commit/1507478a328edf22ebf3ba000a6958270d178aa2 adds a changelog file which may make it easier for some people to find this information.
