### ISSUE TITLE
Fix in elementary appcenter

### ISSUE THREAD

**Issue by btd1337** [mank319/Go-For-It#125]
### Expected behavior
Find the application in any of the categories in AppCenter

### Actual behavior
The application is not listed in any category.

### How to reproduce the behavior
Open the AppCenter in elementary OS.
Search for the application in each of the categories

### Operating System used
elementary OS Loki

### Installation source
Github

**Comment by JMoerman** [comment]
This isn't something I can fix as this is a problem in the search functionality of appcenter.
See https://github.com/elementary/appcenter/issues/864, https://github.com/ximion/appstream/issues/216
