### ISSUE TITLE
Crashes when there's a double space before project tag

### ISSUE THREAD

**Issue by daniellandau** [mank319/Go-For-It#127]
### Expected behavior

App should not crash with valid (or invalid for that matter) input.

### Actual behavior

Outputs 

```
load_task_stores
Reading file: /home/dlandau/Asiakirjat/todo/todo.txt
Reading file: /home/dlandau/Asiakirjat/todo/done.txt
```
and then exits with code `139`. GUI never shows up. Journal has

```
kernel: de.manuel_kehl.[9846]: segfault at 72 ip 0000003153a80526 sp 00007fffb0bb0858 error 4 in libc-2.24.so[3153a00000+194000]
```

### How to reproduce the behavior

Try to open the app with a `todo.txt` with the following contents (notice the double space before `+tag`)

```
2018-02-25 whatever  +tag
```

### Operating System used

Ubuntu 16.04

### Installation source

Installed from Flathub.

```
% flatpak run de.manuel_kehl.go-for-it  --version
Go For It! 1.6.3
Copyright 2014-2017 'Go For it!' Developers.
```

**Comment by JMoerman** [comment]
Thanks for reporting this issue!
This should be fixed with ed31d42e85690bf3f83eddcfcbf4db7940e620e8.
This issue was not limited to tasks with tags, long-ish strings with double spaces would cause crashes.
