### ISSUE TITLE
It's best to name the executable "go-for-it"

### ISSUE THREAD

**Issue by yurivict** [mank319/Go-For-It#128]
You use a very unconventional name here: 
https://github.com/mank319/Go-For-It/blob/master/CMakeLists.txt#L11

**Comment by JMoerman** [comment]
Reverse domain notation is indeed not the norm for Linux/Unix desktop executable names at this moment. It is however used for elementary OS applications, flatpak apps and as far as I know Gnome is switching to it too. (And outside of desktop Linux it isn't unconventional. Look at android if you want a common example.)

Usage of RDNN is however entirely optional, you can use the cmake argument
`-DAPP_SYSTEM_NAME:STRING="go-for-it"`
to use the more conventional naming scheme. This also affects configuration file locations, so you may need to reconfigure _Go For It!_ after switching to a version using an other system name.
