### ISSUE TITLE
Projects...

### ISSUE THREAD

**Issue by damianavila** [mank319/Go-For-It#13]
I know it is planned, but having the possibility to assign task to different projects would be awesome...

**Comment by LeRondPoint** [comment]
Looking forward to this too.... but given the age of this maybe I'll PR it!

**Comment by JMoerman** [comment]
_Go For It!_ now makes clickable links from project and context tags, clicking on them will filter to tasks to only show tasks from the same project or context.

**Comment by JMoerman** [comment]
Support for projects could be improved, but I'm closing this now as any improvements should be considered separate issues.
