### ISSUE TITLE
Done tasks should display a date completed

### ISSUE THREAD

**Issue by shaeenk** [mank319/Go-For-It#134]
I think this feature would be very useful to have and I wouldn't mind if I can assist on developing the feature.

### Expected behavior
Marks completed tasks with an x and should display the date when that was done

### Actual behavior
Marks completed tasks with an x

### Operating System used
linux

### Installation source
sudo add-apt-repository ppa:go-for-it-team/go-for-it-daily && sudo apt-get update
sudo apt-get install go-for-it

**Comment by JMoerman** [comment]
Fixed as of version 1.6.7
