### ISSUE TITLE
Sound notifications with libnotify on Ubuntu 18.04

### ISSUE THREAD

**Issue by anishmittal2020** [mank319/Go-For-It#137]
### Operating System used
Ubuntu 18.04

```bash
$ apt search go-for-it
Sorting... Done
Full Text Search... Done
go-for-it/bionic,now 1.6.5+201812021312~ubuntu18.04.1 amd64 [installed]
```

Libnotify is installed as follows: 
```bash
$ apt search libnotify
libnotify-bin/bionic,now 0.7.7-3 amd64 [installed]
  sends desktop notifications to a notification daemon (Utilities)

libnotify4/bionic,now 0.7.7-3 amd64 [installed]
  sends desktop notifications to a notification daemon
```

But I still don't receive any notification? What should I do?

### Installation source
installed from https://launchpad.net/~go-for-it-team/+archive/ubuntu/go-for-it-daily or built from source_

**Comment by JMoerman** [comment]
Can you clarify if you don't get any notifications or just no sound?

I cannot reproduce this on elementary OS 5.0, which is based on Ubuntu 18.04.
Can you check if https://github.com/mank319/Go-For-It/commit/1fa752f82f6e04c6cc660fe0a490e1a2c3489ede has any effect? (It's part of the 1.6.11 which is already available from the ppa)

**Comment by JMoerman** [comment]
As of e1adf25cd53de91de5aab04c57932e0b0572e97b _Go For It!_ plays its own sound using libcanberra.
