### ISSUE TITLE
Text is not visible in dark theme

### ISSUE THREAD

**Issue by SalahuddinAsh** [mank319/Go-For-It#138]
### Expected behavior
Text of tasks should be visible easily when using dark theme

### Actual behavior
Text is not seen while being in dark theme

### How to reproduce the behavior
Enable dark theme

### Operating System used
Ubuntu 18.04.01

### Installation source
Using sudo apt get go-for-it

**Comment by JMoerman** [comment]
This should be fixed in 1.7, though you may need to change the selected theme in the settings dialog if you use a theme that has a color scheme that differs greatly from Adwaita.

If the issue still exists, please upload a screenshot.

**Comment by wi24rd** [comment]
Suggest default setting to "inherit from Gtk theme", I running the flatpak version which is "elementary" and not dark theme than in my own customized dark theme it like weried:
![image](https://user-images.githubusercontent.com/14029004/57967996-8af75b80-7997-11e9-9866-893ae6cf350d.png)

**Comment by JMoerman** [comment]
When the user hasn't manually set a theme the "Inherit from Gtk" theme is now used unless the desktop theme is either `elementary` or `Adwaita`. The reason for elementary being the default was that the old implementation of reordering rows using drag and drop could look off in certain themes. Looking weird on misbehaving themes (dark only themes have never been supported in Gtk+-3.0) by default was a sacrifice I was willing to make.
