### ISSUE TITLE
Can't add a new list

### ISSUE THREAD

**Issue by maquisard** [mank319/Go-For-It#142]
I am using Go-For-It 1.7.2 on Ubuntu 18.04
I cannot add a new list because the 'Apply' button on the List settings dialog remains disabled. I am not sure if this is a bug or I am using the system wrong. See attached screenshots below.
![Screenshot from 2019-09-03 11-28-35](https://user-images.githubusercontent.com/1199936/64191831-f8dc6b80-ce3e-11e9-9765-dbc1be25c350.png)
![Screenshot from 2019-09-03 11-27-54](https://user-images.githubusercontent.com/1199936/64191842-0265d380-ce3f-11e9-9c54-eea07a7796db.png)

**Comment by JMoerman** [comment]
https://github.com/JMoerman/Go-For-It/commit/ecdaa89463104451160ce35fb139776db5c930a1 should fix this the ppa should have a fixed version within an hour.

**Comment by maquisard** [comment]
thanks
