### ISSUE TITLE
Tell me how to install it on Debian 10 Buster.

### ISSUE THREAD

**Issue by ghost** [mank319/Go-For-It#143]
Tell me how to install it on Debian 10 Buster.
Thank You.

**Comment by JMoerman** [comment]
You can install it either using flatpak (See README.md), or compile it from source:

Terminal commands to compile it from source (assuming the source code has been downloaded (+extracted if not using git) and stored in `path/to/go-for-it-source-code`)
```
sudo apt install valac cmake intltool libgtk-3-dev libglib2.0-dev
cd path/to/go-for-it-source-code
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make
sudo make install
```
