### ISSUE TITLE
Go-for-it  in Dash menu

### ISSUE THREAD

**Issue by davidRFB** [mank319/Go-For-It#146]
Hi ! Thanks for the app. I was wondering if it is possible to have go-for-it in the menu of dash to panel as a quick app or maybe to include it in the notification area of ubuntu. 
![imagen](https://user-images.githubusercontent.com/28023319/92312723-28114580-ef89-11ea-97cb-d18e312b07f2.png)
![imagen](https://user-images.githubusercontent.com/28023319/92312725-2e072680-ef89-11ea-8ec2-f45ba741e705.png)

Thank you for your time and consideration

**Comment by JMoerman** [comment]
This is issue is already tracked in https://github.com/JMoerman/Go-For-It/issues/105 and https://github.com/JMoerman/Go-For-It/issues/104

The next version should include an option to use an AppIndicator. When using gnome https://github.com/ubuntu/gnome-shell-extension-appindicator needs to be installed, but I believe that that extension comes preinstalled on Ubuntu.

I have an extremely basic version already up and running:

![extremely basic indicator](https://user-images.githubusercontent.com/11899523/94344723-85953100-0021-11eb-8206-2c543dbdeb42.png)

Displaying the remaining time, switching to the next task, starting/stopping the timer, etc... from the dock should also be possible in the next version. I have yet to start working on that, though.

**Comment by JMoerman** [comment]
f300ebd3af41815b07799c90640f98c5240cc05f introduces a plugin to show the remaining time in docks supporting the libunity LauncherEntry API (this seems to include dash-to-dock).
![dock-indicator](https://user-images.githubusercontent.com/11899523/96037826-9ee20e00-0e66-11eb-816a-cc276c52c770.png)

dde6bc49574f2b5895f659a74ca9487f3f488d71 introduced an Ayatana panel indicator plugin which currently shows the remaining time and with which you can also start/stop the timer, view the current task and switch to the next or previous task.
Plugin support isn't currently enabled in the daily-builds ppa, this will change at a later point.
