### ISSUE TITLE
App seems broken in Ubuntu 20.04 after last Version (16.11.2020)

### ISSUE THREAD

**Issue by StefanS111** [mank319/Go-For-It#149]
Hello there. I just wanted to open my ToDo and it was taken out of my favourites on the sidelist via the software upgrader and I also can't seem to neither find it anywhere on my system nor start the application in any way. It looks like it was broken via the most recent version. I might be wrong so please update me on what's going on if you have any clues, thanks!

P.S.: It was removed from my favourites list automatically once in the past but I didn't bother much as the app was still on my system.

**Comment by JMoerman** [comment]
Some files were missing in the packaging repo. I'm currently working on getting new builds out, but this will take some minutes.

**Comment by StefanS111** [comment]
Okay. Thank you very much for your quick reply! :+1:

**Comment by JMoerman** [comment]
I hate situations like this... I made sure that the packaging files generated good .deb files, but I forgot to add some new files to the packaging repo. The build logs were fine, everything compiles fine, but launchpad didn't use any of the resulting files resulting in empty packages.
You should be able to download `go-for-it_1.9+202011161654~ubuntu20.04.1` with apt in a few minutes. (And if you are impatient you can download the files here: https://code.launchpad.net/~go-for-it-team/+archive/ubuntu/go-for-it-daily/+build/20306594)

Should you notice any other issues be sure to let me know.

**Comment by StefanS111** [comment]
Thank you very much again. It works fine now :-)
