### ISSUE TITLE
License GPLv3 or later

### ISSUE THREAD

**Issue by dardevelin** [mank319/Go-For-It#2]
Hi, at this point there is no later version to GPLv3 and it seems (from a logical stand point)
that you cannot 'agree' with terms of an unknown license. Therefor even though I understand the
vouch for 'free software foundation' Id strip the 'or later clause' as this may yield unwanted results.

Cheers

**Comment by mank319** [comment]
@dardevelin after thinking about it another time, I have to agree with your reasoning.
