### ISSUE TITLE
[Bug] Timer tab is transparent on Ubuntu 14.10 Unity

### ISSUE THREAD

**Issue by gunzy83** [mank319/Go-For-It#26]
Please see screenshot in link. Other tabs appear fine.

https://www.dropbox.com/s/1n0042326p73tx9/Selection_002.png?dl=0

Thanks.

**Comment by gunzy83** [comment]
Switching GTK theme has no effect on the transparency in that tab. That space at the top that I referred to in my previous comment changes colour (in Ambiance it is grey, in the Royal theme that I am using it is white) so I can only assume that it is supposed to be the background?

On another note, I have installed it on Arch and it works beautifully with the Numix GTK theme in KDE. Must be weirdness in the GTK version in Ubuntu 14.10 :(

**Comment by mank319** [comment]
I just set up a 14.04 VM for testing purposes, where the bug occurs too. So I guess, that it has something to do with Unity. I will further investigate into the issue, but cannot promise that my time allows for such until the end of the month.

**Comment by gunzy83** [comment]
I thought that might be the case with Unity. No rush :) Thanks for looking into it!

**Comment by mank319** [comment]
It seems, as if we are not the only people suffering form that bug: https://twitter.com/d0od/status/551842685024481280

**Comment by popey** [comment]
Apparently disabling overlay scrollbars stops this happening...

**Comment by mank319** [comment]
@popey thanks for that hint! I will try disabling overlay scrollbars, when I have some spare time. If it works, I'd suppose conditionally disabling them based on whether or not the active DE is "Unity". Does anyone know how to check the user's DE from within the code?

**Comment by mank319** [comment]
I just implemented the above strategy, which appears to have fixed the issue on my Ubuntu 14.04 VM. I hope this works as expected for you ;-)

**Comment by mank319** [comment]
I am happy to read, that it works for you @gunzy83!
