### ISSUE TITLE
when compiling in fedora 20, it breaks

### ISSUE THREAD

**Issue by guoyu07** [mank319/Go-For-It#29]
when compiling in fedora 20, it breaks with:

MainWindow.c: In function ‘main_window_task_timer_activated’:
MainWindow.c:1323:3: error: unknown type name ‘GNotification’
MainWindow.c:1327:3: error: unknown type name ‘GNotification’
MainWindow.c:1339:4: error: unknown type name ‘GNotification’
MainWindow.c:1340:4: error: unknown type name ‘GNotification’
MainWindow.c:1353:4: error: unknown type name ‘GNotification’
MainWindow.c:1354:4: error: unknown type name ‘GNotification’
MainWindow.c: In function ‘main_window_display_almost_over_notification’:
MainWindow.c:1404:2: error: unknown type name ‘GNotification’
MainWindow.c:1405:2: error: unknown type name ‘GNotification’
make[2]: *** [CMakeFiles/go-for-it.dir/src/view/MainWindow.c.o] Error 1
make[1]: *** [CMakeFiles/go-for-it.dir/all] Error 2
make: *** [all] Error 2

**Comment by mank319** [comment]
Would you mind compiling the Windows branch for testing purposes once? It does not rely on Glib.Notification.

**Comment by mank319** [comment]
@guoyu07 would you please try again? The latest pull request from @fredmwangi replaced `Glib.Notification` with `libnotify`, thus it may successfully compile without `GNotification` now.

You may have to install the `libnotify` package of course.

Can you confirm, that it works now?

**Comment by mashimom** [comment]
Hello,
I just tried to compile on _Fedora 22 64bit_ and it fails at the `cmake`:
```
...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for modules 'gtk+-3.0;glib-2.0;libnotify'
--   package 'libnotify' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:18 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "$HOME/repos/Go-For-It/build/CMakeFiles/CMakeOutput.log".
```
The package libnotify was already installed:
```
Package libnotify-0.7.6-6.fc22.x86_64 is already installed, skipping.
```

I do not know how to make it work, but I am willing to learn.

**Comment by JMoerman** [comment]
@mashimom do you have the development headers for libnotify installed?
If the headers are installed, please tell me if valac complains when trying to compile something like this:
    
    valac --pkg libnotify some-file.vala

**Comment by fredmwangi** [comment]
@mashimom  On Ubuntu there is a package named: libnotify-dev 
This package contains the development files required in order to compile/build an Application that uses libnotify.
I was not able to locate the equivalent in the Fedora Package Database online.

**Comment by fredmwangi** [comment]
@mashimom You need the equivalent development files for your Fedora system. The package is named: libnotify-devel

Here's a link:
https://apps.fedoraproject.org/packages/libnotify-devel

**Comment by JMoerman** [comment]
Closing this as this issue has not had any responses for months.
