### ISSUE TITLE
Support Gtk < 3.10

### ISSUE THREAD

**Issue by mank319** [mank319/Go-For-It#30]
I have been receiving a considerable amount of requests from users of older distributions, that do not have Gtk 3.10 available. Unfortunately the UI elements used (especially the `Gtk.Stack`) don't allow for lowering that dependency.

That being said, the amount of demand may justify the work it would take to maintain a separate branch, with all the problematic widgets replaced by more traditional ones. I started this issue to coordinate this task and collect a list of steps, that would need to be taken.

- [ ] `Gtk.HeaderBar` can simply be removed. Its content can be moved to a simple toolbar.
- [ ] `Gtk.Stack` + `Gtk.StackSwitcher` must be replaced. Maybe `Gtk.Notebook` is a potential candidate?

**Comment by mank319** [comment]
It would be great, if we'd abstract the MainWindow class in a way, that allows for automatic differentiation between the file to be used in CMakeLists.txt, depending on the available build dependencies.

That being said, we'd have to make sure, that only the differences are maintained in different files and all reusable code resides in the parent class.

**Comment by voldyman** [comment]
Regarding the headerbar issue, I did something similar, made an interface which is implemented by a class for Headerbar and a class for Toolbar and i use the interface in the main window. The main windows uses the headerbar or the toolbar according to a gsettings key. now this works but i am not particularly happy with the code duplication. I'll update when i find a better solution.

**Comment by JMoerman** [comment]
I'm closing this as this has been included in Go For It! for some time now. If issues remain and < 3.10 is still in use this can be reopened.
