### ISSUE TITLE
Indicator

### ISSUE THREAD

**Issue by malteneuss** [mank319/Go-For-It#32]
I believe that a little indicator up in the taskbar that starts automatically is helpful.
It could show the current task as well as the remaining time so that you don't have to swich to the app.

**Comment by mank319** [comment]
Yeah I have thought about that before. Which behavior would you prefer?

1. Show an indicator as soon as the application is running
2. Show an indicator as as soon as the timer is running
3. Only show an indicator if the timer is running in the background

I personally think that either 2. or 3. would be the nicest way to handle this.

**Comment by malteneuss** [comment]
Personally, since i use the app from the minute i start my pc, i would prefer 1. because then if you put the app on autostart you can always access it from the same location.
Otherwise i suggest 2., because i believe that people mostly leave the app in the background to use the whole screen space for work.

**Comment by fredmwangi** [comment]
Careful consideration should be taken before creating an app indicator. I definitely see the appeal--especially for an app like Go For It!, which is always running (at least for me it is). A nice implementation of this can be seen with the [Pomodor Indicator](https://launchpad.net/pomodoro-indicator). It is solely a panel app indicator. 

Option 3 as a Default would probably work the best and is in accordance with the [Human Interface Guidelines](http://elementaryos.org/docs/human-interface-guidelines/system-indicators). The Go-For-It App should not become yet another application cluttering the panel. Having both an app indicator in the panel and the application is open can become redundant.

Overall, if an app indicator for Go For It! is created, the user can always be given the choice of behavior in preferences.

**Comment by mank319** [comment]
@fredmwangi I completely agree with your arguments. Option 3 would make a good default and the preferences dialog could offer other choices, as well as an option to disable it completely.

**Comment by orschiro** [comment]
Another idea inspired by Thunderbird:

![image](https://cloud.githubusercontent.com/assets/170947/7333339/0830dbda-eb6c-11e4-8e6f-12818da4941c.png)

Could we let Go For It display the remaining minutes in a similar way in the Plank dock icon?

**Comment by JMoerman** [comment]
Implemented in f300ebd3af41815b07799c90640f98c5240cc05f (libunity LauncherEntry API) and dde6bc49574f2b5895f659a74ca9487f3f488d71 (Ayatana indicator)
