### ISSUE TITLE
Notification sounds

### ISSUE THREAD

**Issue by mank319** [mank319/Go-For-It#33]
Several people have requested dedicated sound effects for _Go For It!_, especially when a timer/break iteration finishes.

**Comment by gaoyanglion** [comment]
yes,it is very useful when paying attention to something

**Comment by mank319** [comment]
We are already past that version :laughing:
A milestone will be reassigned if a solution is in sight :wink:

**Comment by xordspar0** [comment]
What do you think about using libcanberra? It's an additional dependency, but it is kind of Gnome-y.

**Comment by JMoerman** [comment]
Implemented in e1adf25cd53de91de5aab04c57932e0b0572e97b (uses libcanberra)
