### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by mank319** [mank319/Go-For-It#35]
At this stage of development I'd consider translation support a nice feature.

This [blog post](http://www.teejeetech.in/2013/03/vala-6-localization.html) appears to give a comprehensive introduction into the topic. It doesn't look too complicated. 

I will start investigating into it, when I have more spare time (~ February). If anyone else wants to give it a try, just assign yourself to the issue, so I can see, that you are already working on it.

**Comment by mank319** [comment]
I have a very hard time getting `gettext` to work on Windows, therefore this feature must be delayed to a later milestone.

**Comment by mank319** [comment]
If you have a look at the source code, you'll see that I already made all UI strings translatable.
Unfortunately I am very busy with uni assignments right now, so I barely have any time for free time coding...

Setting up the `gettext`  pipeline so that people can easily submit translations is however among the first tasks that I will tackle when I continue to work on the app :wink:

**Comment by JMoerman** [comment]
Translations are now installed to and loaded from $install_prefix/share/locale. Go to https://translations.launchpad.net/go-for-it to translate _Go For It!_. (If any problems arise, feel free to contact me. I still have to get used to launchpad.)

**Comment by troe** [comment]
why not use the service https://www.transifex.com/
