### ISSUE TITLE
Change the cursor when hovering the dragging area

### ISSUE THREAD

**Issue by waldyrious** [mank319/Go-For-It#36]
Preferably into the gtk equivalent of the `ns-resize` (up-down arrow) or `grab` (hand) cursors in [css](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#Values).

**Comment by mank319** [comment]
That is a nice idea :+1: Thanks!
After all it's little details like that, which make a UI elegant and comprehensible.

**Comment by JMoerman** [comment]
Implemented in 44f62a5f0705e3ab723c4d4277ec7fd2e08dd597
