### ISSUE TITLE
Completed tasks are marked incorrectly

### ISSUE THREAD

**Issue by xordspar0** [mank319/Go-For-It#39]
The Todo.txt format specifies that done tasks should be marked with an "x" followed by a space. Go For It currently doesn't include that space, so other Todo.txt applications don't recognize the tasks as done.

**Comment by xordspar0** [comment]
Source: https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space

**Comment by mank319** [comment]
Thanks @xordspar0 for pointing that out and fixing it already :+1:
