### ISSUE TITLE
Don't require to manually select a todo.txt directory

### ISSUE THREAD

**Issue by danrabbit** [mank319/Go-For-It#4]
So part of our HIG is never asking users to make technical decisions. Having to select a todo.txt directory puts an extra step in between the user and getting started with your app.

However, I understand the desire to want to show users that they *can* set this. So I think I would instead create the todo in a sane default location and then leverage a unique advantage of your app to help guide users: pre-populate with some todos :)

I would make two default todos:
"Support Go For It! by making a donation" and "Select a location for todo.txt by clicking the menu in the bottom right corner". This would preserve your intent with the welcome screen while also showing users how to use your app.

But if you insist on the dialog... It should probably be modal. At the moment, I can start using the app without dismissing this dialog, which seems kind of weird.

Ideally though, a welcome should be embedded in the main view and not be a separate dialog and only be used if it absolutely necessary to block the user before they can start using your app.

**Comment by mank319** [comment]
I finally implemented this. Took a while as I considered several things (both in real life and in this particular project) of higher priority... But I really prefer it this way. Thanks again for your input @danrabbit :wink:
