### ISSUE TITLE
Can't minimize and would better to have a notification icon

### ISSUE THREAD

**Issue by THPubs** [mank319/Go-For-It#42]
Im using Ubuntu and Unity. When I launch the app, I can't minimize it. No minimize button. It would be better if it minimize as soon as we start the timer giving way for us to do the work :-)

It would also be better if the dash icon will disappear and use a notification icon to handle the work like most of the background apps.

**Comment by mank319** [comment]
Hey @THPubs thanks for your feedback. First of all whether or not you have a minimize button is up to your window manager. Unfortunately Unity does not play well with client side decorated windows, so in the long run it might be best to maintain an option to move all contents of the header bar into a separate tool bar to avoid CSDs. 

I also agree, that an "auto minimize" option would be pretty nice!

We already collected thoughts about a potential indicator icon in #32.

Thus I will close this issue and extract two different tasks according to the description above.

**Comment by THPubs** [comment]
@mank319 Perfect! Thanks for the quick response! :-) I really like the project!

**Comment by mank319** [comment]
@THPubs No problem. As I said, the "auto minimize" idea is really good and feedback is always appreciated :wink:
