### ISSUE TITLE
Button "Close" on "About" page isn't working

### ISSUE THREAD

**Issue by Opennat** [mank319/Go-For-It#45]
You can close "About" window only by Alt-F4 or by hitting "X" in top left.
GoForIt 1.4.1. Ubuntu 14.04.

**Comment by jhol** [comment]
Pressing Escape works also.

**Comment by mank319** [comment]
It appears to work on some DEs but not on all...
@jhol are you also on Unity?

**Comment by jhol** [comment]
I'm on Linux Mint/Cinnamon

**Comment by rustedwolf** [comment]
Same on my Linux Mint 13 (0lder version of GTK+)

**Comment by rustedwolf** [comment]
I'm not familliar with Vala, but I've noticed the Close buttons at the settings and about dialog are different, so does the events used to call the destroy() method:
SettingsDialog.vala line 63 (the working one)
```vala
        if (response == Gtk.ResponseType.CLOSE) {
```
AboutDialog.vala line 50
```vala
        if (response == Gtk.ResponseType.DELETE_EVENT) {
```
Maybe this buttons sends not the DELETE_EVENT but some kind of other like Cancel event or something?

**Comment by mank319** [comment]
@rustedwolf thank you for that hint :+1: 
The bug has been fixed :heavy_check_mark:

**Comment by rustedwolf** [comment]
No problem!
PS. Glad, you've liked the coffe. ;)
