### ISSUE TITLE
Recurring Tasks

### ISSUE THREAD

**Issue by TheEndIsNear** [mank319/Go-For-It#47]
Would like to be able to add daily tasks, or recurring tasks to the list of todo items. Not sure if this is supported by todo.txt or not.

**Comment by mank319** [comment]
@TheEndIsNear chances are this functionality might be added in terms of an external application: https://plus.google.com/+JonathanMoerman/posts/1CFmso8qYJf

I am in touch with the developer and as soon as his app supports (automatic) exporting to Todo.txt you can use it to manage your recurring tasks and start Go For It! to work on your daily tasks.

Would you consider this a satisfactory solution?
Of course one could consider integrating such a function into Go For It!, but I personally consider other tasks of higher priority, e.g. project and context support.

**Comment by TheEndIsNear** [comment]
That looks like a good solution, no need to reinvent the wheel, if someone else is working on it.

**Comment by mank319** [comment]
So I close this issue for now. As said above: It may be reopened, whenever we feel the need to do so :wink:

**Comment by dacoex** [comment]
> @TheEndIsNear chances are this functionality might be added in terms of an external application: https://plus.google.com/+JonathanMoerman/posts/1CFmso8qYJf
> 
> I am in touch with the developer and as soon as his app supports (automatic) exporting to Todo.txt you can use it to manage your recurring tasks and start Go For It! to work on your daily tasks.

Since Google Plus is now closed, what solution / software was the above link related to?
Or, which method do you recommend to manage recurring tasks or tasks that stretch over several days?

**Comment by JMoerman** [comment]
The solution above never came to be. I do plan to add support for supporting recurring tasks to _Go For     It!_, but it will need to have a more powerful backend first (todo.txt is not really suitable for storing the metadata needed to properly support recurring tasks).

In the meantime you could make a script that periodically adds tasks to the todo.txt file you use. A possible disadvantage of this is that you may end up with duplicate tasks if you don't complete tasks in time, which could be a bit annoying if you, for example, have daily tasks that do not carry over to the next day.
