### ISSUE TITLE
Use Granite.Widgets.About

### ISSUE THREAD

**Issue by danrabbit** [mank319/Go-For-It#5]
We made a sexy stock About dialog with all the things elementary OS users expect to see. It would be great for Go For It! to be consistent with the system in using this dialog

**Comment by fredmwangi** [comment]
![recorded](https://cloud.githubusercontent.com/assets/10415947/5717002/03845cba-9ac7-11e4-8617-86d70d3a2b13.gif)

How it would look

**Comment by fredmwangi** [comment]
How it would look.
![recorded](https://cloud.githubusercontent.com/assets/10415947/5717051/b4159666-9ac7-11e4-8a81-41aa52cb41c5.gif)

**Comment by fredmwangi** [comment]
![recorded](https://cloud.githubusercontent.com/assets/10415947/5717063/eb5780da-9ac7-11e4-89ec-ecacfc7cacf8.gif)

How it would look.

**Comment by fredmwangi** [comment]
![bildschirmfoto vom 2015-01-13 01 29 15](https://cloud.githubusercontent.com/assets/10415947/5717072/110c28f8-9ac8-11e4-97cd-50385aa4e3c8.png)

What it would look like.

**Comment by fredmwangi** [comment]
What it would look like:
![bildschirmfoto vom 2015-01-13 02 04 10](https://cloud.githubusercontent.com/assets/10415947/5717089/8bd0eed4-9ac8-11e4-8a8b-a2f723508ee3.png)

**Comment by fredmwangi** [comment]
scrolling
![ercrcs](https://cloud.githubusercontent.com/assets/10415947/5717132/29d7a230-9ac9-11e4-9e8c-fd296da8b395.gif)

**Comment by fredmwangi** [comment]
scrolling:
![recorded](https://cloud.githubusercontent.com/assets/10415947/5717148/7e3ddd8a-9ac9-11e4-8f61-3ceadcebb738.gif)

**Comment by fredmwangi** [comment]
scrolling:
![recorded](https://cloud.githubusercontent.com/assets/10415947/5717208/8f198554-9aca-11e4-9cbc-7f66efa788b2.gif)

**Comment by fredmwangi** [comment]
scrolling:
![arst](https://cloud.githubusercontent.com/assets/10415947/5717229/f23e0e02-9aca-11e4-810b-035623755c07.gif)

**Comment by mank319** [comment]
@fredmwangi it looks very nice indeed.

**Comment by mank319** [comment]
I have made up my mind about how to solve the "Granite vs No-Granite" issue in that particular case:

- [ ] The constructor of `AboutDialog` shall accept a list of all the necessary fields; especially those that change regularly, like version

- [ ] Duplicate `AboutDialog.vala` to `AboutDialog_no_granite.vala`

- [ ] Replace `Gtk.AboutDialog` with `Granite.AboutDialog` in `AboutDialog.vala`

- [ ] Define a rule in `CMakeLists.txt` that determines, whether or not the *Granite* build dependencies are available and therefore decides whether or not to include `AboutDialog.vala` or `AboutDialog_no_granite.vala`

This way I can simply set up another PPA, with elementary (and thus Granite) dependencies for us elementary users and leave the other one for the rest of the (Ubuntu based) world. If Granite is included in a future version of Ubuntu, the Launchpad buildbot will automatically use the Granite version, without us applying any changes. And for those who compile themselves it will work *magically* :+1: 

This will keep the maintenance overhead as low as possible!

**Comment by mank319** [comment]
Unfortunately I am currently in an exam period and thus don't have much time for changes like that. That being said it should not be much work, if you know your way around `CMake` (at least I hope so :wink: ).

Pull requests and feedback are welcome!

**Comment by JMoerman** [comment]
Implemented in 23cc02111af46944f27fb7394d34ec7a3e0c92dc.
