### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by xordspar0** [mank319/Go-For-It#55]
Go For It should add creation and completion dates to new and completed items, respectively.

See relevant documentation:
![Creation date](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#rule-2-a-tasks-creation-date-may-optionally-appear-directly-after-priority-and-a-space)
![Completion date](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space)

**Comment by xordspar0** [comment]
If this is implemented, then the dates should be hidden from the names of the tasks because it makes things too bulky. There should be another way to look at the date.

**Comment by mank319** [comment]
I agree. They should not be directly exposed to the user, but it should be possible to filter and/or sort by that attribute.

**Comment by JMoerman** [comment]
Supported since 1.6.7
