### ISSUE TITLE
win32:malware-gen (avast antivirus false-positive?)

### ISSUE THREAD

**Issue by zeblau** [mank319/Go-For-It#58]
Is there a way to know for sure the windows client is not virus infected, e.g. false positive?

**Comment by mank319** [comment]
I am going to compile it again and install Avast on my Windows VM, that I have set up for the sole purpose of installing *Go For It!*. Thanks for reporting - if there was anything wrong, we'd need to fix that as soon as possible!

**Comment by mank319** [comment]
You can also compile it with the script `winbuild.bat` in the windows branch. You need `Gtk 3.10` and `valac 0.24`, which is a pain to install on Windows - but possible.

**Comment by mank319** [comment]
I disabled the Windows download for now, until we got this sorted!

**Comment by mank319** [comment]
I compiled it again with the newest sources, new GTK release and, as said earlier, on a recently installed VM. Scanning with Avast does not show any suspicious activity.

I have no idea why you have experienced the issue, but it is fixed now! If my old VM was not infected by some sort of malware that attaches itself to binaries, there must be a "harmless" explanation. Maybe the  Installer Studio created suspicious patterns of some sort?

I have just composed a blog post to inform users about the incident and about actions to be taken.
Thanks so much for reporting this @zeblau!

By the way: Could you please confirm, that the [recent version](http://manuel-kehl.de/projects/go-for-it/download-windows-version/) passes the Avast test on your system too?

**Comment by zeblau** [comment]
At work we have Symantec Endpoint Protection, which pop-upped saying that the windows build of Go-For-It was "seen" less than 50 times, which makes sense, but otherwise no problems. Now, I scanned with Malwarebytes Anti-malware at work, and there is really no problem here at the moment. So my suspicion is that it is just a false-positive and no worries. I will scan the latest windows build at home with Avast. And let you know.

**Comment by jamtraks** [comment]
my avg anti virus software keeps detecting this "win32:malware-gen" at the end of each launcher download and will not allow openrct to run. I was told that it is a false positive and nothing to worry about, anyone know what this is and why i'm getting this message, is a separate virus/malware injecting or initiating this file, or is this something that is attached to the launcher's download? and if so ... why>?

**Comment by JMoerman** [comment]
@jamtraks Did you mean to post here? You're speaking of openrct and a launcher, which doesn't have anything to do with _Go For IT!_.
