### ISSUE TITLE
Drag area disappears on all items if one item is too long

### ISSUE THREAD

**Issue by johannesgunnar** [mank319/Go-For-It#60]
![screenshot from 2015-05-08 10 32 17](https://cloud.githubusercontent.com/assets/2924543/7534786/88c0ee60-f56d-11e4-8ea2-a6f83ff0a62d.png)
Dragging gets a little bit tricky if one or more items are longer than the window as the drag handle disappears. It is possible to drag without using the drag handle, but that only works if you don't have the todo item selected before hand. (I'm using Ubuntu 14.10)

**Comment by mank319** [comment]
Thanks for reporting. This behaviour has been bugging me for quite a while already :+1:
I have been brainstorming about alternative ways to hide/expose additional details lately.
What would you think about cutting all text according to window size, while expanding the currently selected entry to a multi line text field?

**Comment by johannesgunnar** [comment]
Yes, pretty much.

The behaviour I would expect would be that text would be cut but drag handle always be visible in a fixed position on the right. Then pretty much what you said, selected entry should expand to show the rest of it.

**Comment by JMoerman** [comment]
This should no longer happen in 1.6
