### ISSUE TITLE
Software recommendation for Android sync

### ISSUE THREAD

**Issue by orschiro** [mank319/Go-For-It#62]
Hi all,

A quick question to those of you who use Go For It (and its backend todo.txt) in conjunction with an Android device. Do you use the [official client](https://play.google.com/store/apps/details?id=com.todotxt.todotxttouch) (slightly outdated client 11.11.2013) or can you recommend me a better alternative?

Thankfully,

Robert

**Comment by mank319** [comment]
Hi @orschiro. 
I personally use the official client and it works very well for me. Especially the widget is a nice addition.
[Simpletask] appears to be a promising alternative worth trying.

**Comment by mank319** [comment]
ITSFOSS has published an article about setting up *Go For It!* with *Simpletask*: http://itsfoss.com/go-for-it-to-do-app-in-linux/

**Comment by orschiro** [comment]
> ItsFOSS has published an article about setting up Go For It! with Simpletask: http://itsfoss.com/go-for-it-to-do-app-in-linux/

I was lazy and just followed this guide. Turned out to work perfectly. Thanks for referring to it!

Maybe both apps (and the tutorial) could be added to `Storage and Synchronisation` in the `README`?

**Comment by mank319** [comment]
Good idea! Thanks :+1:
