### ISSUE TITLE
Notifications not working?

### ISSUE THREAD

**Issue by thofsaw** [mank319/Go-For-It#63]
I apologise in advance if this is a user problem, however, notifications don'e seem to appear for me.  I've tried the default of 60secs and also 5secs to see if I'm just missing them.  No Joy.

Using Ubuntu 14.04 64bit
Using go-for-it 1.4.3

**Comment by thofsaw** [comment]
Ok, I think I realise what's going on here.  It has turned out to be user error.  I had thought that the "reminder notification" setting meant that *every* 60 seconds, a notification would pop-up to remind me to keep on task.  
It has become clear that the notification will appear 60 seconds before a timer boundary - ie. before the break and before the next task.

Now, I haven't closed this just yet - I wondered whether this might be something to be made clearer somehow... or perhaps whether this might be a feature worth considering to include?  This could obviously become an annoyance, but perhaps for longer tasks, some kind of reminder every now and then might be helpful?

**Comment by mank319** [comment]
Hey @thofsaw thanks for your feedback - you made some interesting points there!

I changed the reminder label to something more explanatory to avoid misunderstandings in the future :wink: 

I think regular reminders really are too disturbing, but a "minimalist always on top floating overview window" displaying the current task and time is planned for the future. This would help to keep the focus on the task, wouldn't it?

**Comment by thofsaw** [comment]
No worries, thanks @mank319.

Personally, I easily get distracted, so I find having a reminder helpful.  For example, hamster time-tracker implements this and I don't find it too annoying.

However I like your idea of a floating always-on-top window option.  That might work.
