### ISSUE TITLE
Add localization (gnu gettext)

### ISSUE THREAD

**Issue by Yanpas** [mank319/Go-For-It#66]
The app is english-only

**Comment by mank319** [comment]
Some time ago I started working on a 'gettext' enabled branch (locally), but had problems getting it to work under Windows.
I'd suppose to implement it as a "Linux only" feature for now until anyone wants to help with this.

**Comment by nodiscc** [comment]
duplicate of https://github.com/mank319/Go-For-It/issues/35 ?

**Comment by Yanpas** [comment]
yes
