### ISSUE TITLE
No icon on XFCE

### ISSUE THREAD

**Issue by Yanpas** [mank319/Go-For-It#67]
XFCE panel no icon
![_2015-10-07_17-44-48](https://cloud.githubusercontent.com/assets/7345761/10340970/45312324-6d1b-11e5-95a8-dbaf369f16b1.png)

**Comment by mank319** [comment]
Thank you for pointing this out @Yanpas.
If anyone has experienced similar behaviour in the past, please point out what the cause could be.
I am grateful for every hint :wink:

**Comment by JMoerman** [comment]
I just reproduced it on xubuntu 15.04.
As far as I can tell the .desktop file doesn't seem to be the cause of the problem.
I used another application's .desktop file as a template and the issue still occurred.

**Comment by Yanpas** [comment]
S me happens with several gnome apps (baobab etc.) It seems that gtk3 and gnome has modified standart which defines the icon location recently

**Comment by bil-elmoussaoui** [comment]
I've pushed a commit to fix this, you can try adding `StartupWMClass=go-for-it` to your desktop file just like in the commit https://raw.githubusercontent.com/bil-elmoussaoui/Go-For-It/b274feb435e229754797719e99d1c7d4aeb1acb7/data/go-for-it.desktop . Close the application and open it again, everything will work as expected :+1:

**Comment by Yanpas** [comment]
Thanks!
