### ISSUE TITLE
[bug] default tasks re-appear when pressing Refresh

### ISSUE THREAD

**Issue by nodiscc** [mank319/Go-For-It#73]
Hitting the `Refresh` menu entry at any time makes the default tasks re-appear in the task list

```
Choose Todo.txt folder via "Settings"
Consider a donation to help the project
Spread the word about "Go For It!"
Consider contributing to the project
```

This looks like a nice application aside from this problem

**Comment by mank319** [comment]
Mhh strange, I cannot reproduce that behaviour on my current setup, even if the task list is empty.
I will however keep an eye on it and try to think of possible causes :wink:

Does it happen *every* time or just under certain circumstances, e.g. with an empty todo list?

**Comment by nodiscc** [comment]
Hi, it happens every time here (Debian stretch). Contents of done.txt/done.txt seem to have no influence over this behavior.
