### ISSUE TITLE
Add time in done list

### ISSUE THREAD

**Issue by wlyan** [mank319/Go-For-It#74]
Please add the time when task was marked done in done.txt file.

**Comment by heatfx** [comment]
I also think it is useful to record when the task is created or done.

**Comment by baimafeima** [comment]
Or to add how much time was spend on a task in case it was actively tracked.

**Comment by JMoerman** [comment]
This was implemented in the later 1.6 releases
See https://github.com/mank319/Go-For-It/issues/49 / https://github.com/JMoerman/Go-For-It/issues/15 for time tracking
