### ISSUE TITLE
Problem with Unix and Windows line breaks

### ISSUE THREAD

**Issue by mank319** [mank319/Go-For-It#77]
A comment on the project's website describes the following bug:

> There is one small issue I found: I am using a shared file via dropbox between Windows, Linux and Android. The problem is the CTRL-Ms in the carriage return code from Windows which seem to disturb the layout.
> Testcase: edit on linux; close GoForIt; edit on windows; close GoForIt; next time I open GoForIt anywhere the file has CTRL-Ms at the end of each task which are then shown as empty lines.
> Fix: either ignore the CTRL-Ms when displaying or write to file in Linux/Unix format and not Windows.

**Comment by JMoerman** [comment]
Just fixed this, using unix line ending on Windows wouldn't be a good fix because a user could still use another windows todo.txt application. Go for it would also parse empty lines as tasks with empty names, I think it's better to ignore those lines.

**Comment by mank319** [comment]
Thanks @JMoerman for your support :+1:
