### ISSUE TITLE
Design problem in unity.

### ISSUE THREAD

**Issue by nmabhinandan** [mank319/Go-For-It#79]
The Gnome applications like `gnome-boxes` have buttons in title bar just like go-for-it has. But they appear correctly in Unity title-bar but go-for-it buttons do not.

![go for it _005](https://cloud.githubusercontent.com/assets/1548848/11783499/a59fb632-a29d-11e5-9a5d-105d607b442b.png)

**Comment by nmabhinandan** [comment]
![boxes_008](https://cloud.githubusercontent.com/assets/1548848/11783592/0f6e73f0-a29e-11e5-8f2f-773626b0d5e8.png)

**Comment by JMoerman** [comment]
This is not a bug, Go for it does not use a headerbar in desktop environments that don't properly support clientside decorations. At this moment in time there is no way to configure this behavior.

**Comment by JMoerman** [comment]
You could trick Go for it! in to thinking it can use a headerbar by starting Go for it! like this, though:

    export DESKTOP_SESSION=gnome && go-for-it

**Comment by nmabhinandan** [comment]
But it's working fine for `gnome-boxes` and other gnome applications.

**Comment by JMoerman** [comment]
Unity used to have bad support for CSD, you wouldn't be able to properly resize windows, things looked out of place, etc...
Unpatched nautilus and gedit use a headerbar, but canonical maintains headerbar less versions of this app.
On my local you can configure if a headerbar is used or not, expect to see it in version 2.0.

**Comment by nmabhinandan** [comment]
:+1:
