### ISSUE TITLE
advice for go-for-it

### ISSUE THREAD

**Issue by congleetea** [mank319/Go-For-It#82]
Now I use go-for-it to manager the things I will do, But I have some idea for it. if user can change the order of transaction, I think it will be better. thanks.

**Comment by JMoerman** [comment]
What do you mean with transaction? I assume you were referring to the tasks.

You can already reorder tasks by dragging them with the mouse pointer, you may have meant that you would like an option to sort the tasks automatically, that is something that should appear in a future version.

**Comment by congleetea** [comment]
Yes, It's tasks. I didn't know there can reorder tasks by dragging them. Thanks a lot and expects your new feature.
