### ISSUE TITLE
Bug on first run: endless loop of "support go for it" in list

### ISSUE THREAD

**Issue by rhoconlinux** [mank319/Go-For-It#83]
Hello!
I found this weard behavior. Downloaded the latest version from the ppa (14.04 x64) and the first run was a little bit heavy, the program didn't responded, so I closed it and run it again. I found my todo.txt filled with:
-Spread the word about "Go for it!"
-Consider a donation to help the project
-Consider contributing to the project
![](http://i.imgur.com/WZT4ze9.jpg)
And here is the todo.txt
![](http://i.imgur.com/hlcURzI.png)
The sequence repeated lots of times (and probably might continue if I didn't closed the program when I did). 
So, I'm reporting it. Probably is something silly, but it is critical for a someone that is having a first contact with the program cause directly affects both user experience and program performance.
Cheers and keep the good work!
:+1:

**Comment by JMoerman** [comment]
I was aware of some buggy behavior but I hadn't fixed it because it didn't seem to cause any real problems and I am already working on a newer version of go for it (If the code design of the architecture is indeed good enough). 

Give me a few mins to fix it. :)

**Comment by JMoerman** [comment]
If you want a fixed version right now, compile from https://github.com/JMoerman/Go-For-It/tree/Go-For-It-1.x
It'll probably take a bit of time to reach the ppa, @mank319 will have to take it from here.

**Comment by mank319** [comment]
@rhoconlinux thanks for reporting and @JMoerman thanks for stepping in so quickly and being such an active contributor/team member :wink: :+1:
I'll make sure to review and merge the changes into master as well as update the PPA today!

**Comment by mank319** [comment]
Fixes have been reviewed and merged. PPA is up to date now. Thanks everyone :wink:
