### ISSUE TITLE
PPA doesn't work in Ubuntu 16.04

### ISSUE THREAD

**Issue by forteller** [mank319/Go-For-It#86]
Hope you'll be able to fix this soon. Thanks! :)

**Comment by mank319** [comment]
The build process is currently [running and apparently it is looking good so far](https://code.launchpad.net/~mank319/+archive/ubuntu/go-for-it/+recipebuild/1123619). You should be able to install it within the next hour or so :wink:

**Comment by forteller** [comment]
I was! Thank you! :D

**Comment by mank319** [comment]
Your're welcome :wink:
