### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by JakubJecminek** [mank319/Go-For-It#90]
Hello, I really like this application but I've noticed that there are no keyboard shortcuts. This is productivity killer for me. Are there any plans for adding keyboard shortcuts? Thank you. #

**Comment by JMoerman** [comment]
Shortcut keys for selecting tasks from the timer was mentioned here: https://github.com/mank319/Go-For-It/issues/54
Making the application more keyboard friendly is indeed a nice improvement, but I wan't to implement some other things first and will be unable to work on Go For It! for ~two weeks.
@mank319 could implement it in the mean time, though.

**Comment by mank319** [comment]
I am currently finishing my MSc thesis :mortar_board: , so for the next weeks I am already pretty much occupied. Sorry :laughing:

**Comment by JMoerman** [comment]
1.8 will include some shortcuts that make navigating the application a little easier.
See https://github.com/JMoerman/Go-For-It/blob/6e75e5ae643151c403db911f6fb335c9992aa967/src/view/MainWindow.vala#L255 for  the shortcuts that are currently implemented.

**Comment by Elm7** [comment]
Hi, is there a way to customize shortcut (jk are not well placed since I use bépo (french eq to dvorak)) ?
Thanks !

**Comment by JMoerman** [comment]
> Hi, is there a way to customize shortcut (jk are not well placed since I use bépo (french eq to dvorak)) ?
> Thanks !

Not right now (outside of editing src/Shortcuts.vala), but shortcuts support is something that is far from being completed. Feel free to submit patches or offer suggestions. 1.8 (shortcuts are currently only available in the unstable (as in unfinished and subject to change) git versions) may include a way to edit the shortcuts, but as this isn't something completely trivial I haven't done so yet.
