### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by jgjimenez** [mank319/Go-For-It#92]
I would love to translate it into Spanish.

**Comment by JMoerman** [comment]
Sorry for my late response.

Hi, I just [added](3649a04c4d0aadcd5b23cbfb0b4d03522efc76b6) the necessary files and changes to update and install translations.
I'll probably make it translatable via launchpad, but I don't have any experience with that and I haven't got the time to look into it right now.

If you want to translate it right now, you could use a tool like [poedit](https://poedit.net/) and make a pull request.

**Comment by JMoerman** [comment]
I registered the project on launchpad and configured translations, you should be able to translate the project here: https://translations.launchpad.net/go-for-it/trunk/+pots/go-for-it/es/+translate

**Comment by JMoerman** [comment]
I just imported it: 6350f7015b19a9d50e1ff860654ec087c84b3510
![schermafdruk van 2016-11-22 13 38 21](https://cloud.githubusercontent.com/assets/11899523/20524148/5237c7de-b0b9-11e6-8be4-2e737adc73e8.png)

Thanks for your contribution!
