### ISSUE TITLE
The software crashes if its todo.txt directory on a read-only disk

### ISSUE THREAD

**Issue by mevsme** [mank319/Go-For-It#99]
Ubuntu 15.04
v 1.4.7

Sometimes Windows10 blocks the disk with some hibernation crap (to start faster) and I can not mount it in a normal mode. So when I mounted it in a 'read-only' mode, **Go for it!** crashes when I want to add something in the list.

**Comment by JMoerman** [comment]
Actually, it probably doesn't crash, but outputs an error message on the command line and aborts.

An error dialog, not aborting and not performing any io operations on the current .txt files would probably be a better way to handle io errors.

You should be able to disable hibernation and hybrid boot, btw.
